In [3]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

poke_data = pd.read_csv('Documents/pokemon.csv', index_col=None, na_values=['NA'])

In [126]:
poke_data.head()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0

In [127]:
pokebasics = poke_data[['name','type1','type2','attack','sp_attack','defense','sp_defense','speed']]

In [128]:
poketype = pokebasics[['name','type1','type2']]

In [129]:
poketype[(poketype['type1']=='bug') & (poketype['type2']=='poison')]

           name type1   type2
12       Weedle   bug  poison
13       Kakuna   bug  poison
14     Beedrill   bug  poison
47      Venonat   bug  poison
48     Venomoth   bug  poison
166    Spinarak   bug  poison
167     Ariados   bug  poison
268      Dustox   bug  poison
542    Venipede   bug  poison
543  Whirlipede   bug  poison
544   Scolipede   bug  poison

In [130]:
poketype[(poketype['type1'].isin(['bug','poison'])) & (poketype['type2'].isin(['bug','poison']))]

           name   type1   type2
12       Weedle     bug  poison
13       Kakuna     bug  poison
14     Beedrill     bug  poison
47      Venonat     bug  poison
48     Venomoth     bug  poison
87       Grimer  poison  poison
88          Muk  poison  poison
166    Spinarak     bug  poison
167     Ariados     bug  poison
268      Dustox     bug  poison
450     Skorupi  poison     bug
542    Venipede     bug  poison
543  Whirlipede     bug  poison
544   Scolipede     bug  poison

In [153]:
poketype2 = poketype.copy()

In [154]:
#Pokemon with no dual types are doubling types (Grimer, Muk, Charmander, etc...), 
#let's fix that by making the type2 Null if they match type1

poketype2.loc[poketype2['type1']==poketype2['type2'],'type2'] = None

In [164]:
pokebasics[pokebasics['type1']=='bug'].sort_values(by='speed')

           name type1     type2  attack  sp_attack  defense  sp_defense  speed
212     Shuckle   bug      rock      10         10      230         230      5
203      Pineco   bug       NaN      65         35       90          35     15
265     Silcoon   bug       NaN      35         25       55          25     15
267     Cascoon   bug       NaN      35         25       55          25     15
264     Wurmple   bug       NaN      45         20       35          30     20
588  Escavalier   bug     steel     135         60      105         105     20
615     Shelmet   bug       NaN      40         40       85          65     25
400   Kricketot   bug       NaN      25         25       41          41     25
45        Paras   bug     grass      70         45       55          55     25
664      Spewpa   bug       NaN      22         27       60          30     29
10      Metapod   bug       NaN      20         25       55          25     30
46     Parasect   bug     grass      95         60       80          80     30
166    Spinarak   bug    poison      60         40       40          40     30
13       Kakuna   bug    poison      25         25       50          25     35
663  Scatterbug   bug       NaN      35         27       40          25     35
736   Charjabug   bug  electric      82         55       95          75     36
411       Burmy   bug       NaN      29         29       45          45     36
412    Wormadam   bug     grass      69         69       95          95     36
291    Shedinja   bug     ghost      90         30       45          30     40
289     Nincada   bug    ground      45         30       90          30     40
415   Vespiquen   bug    flying      80         80      102         102     40
767   Golisopod   bug     water     125         60      140          90     40
167     Ariados   bug    poison      90         60       70          70     40
204  Forretress   bug     steel      90         60      140          60     40
539    Sewaddle   bug     grass      53         40       70          60     42
540    Swadloon   bug     grass      63         50       90          80     42
737    Vikavolt   bug  electric      70        145       90          75     43
47      Venonat   bug    poison      55         40       50          55     45
9      Caterpie   bug       NaN      30         20       35          20     45
557     Crustle   bug      rock     105         65      125          75     45
..          ...   ...       ...     ...        ...      ...         ...    ...
282     Surskit   bug     water      30         50       32          52     65
413      Mothim   bug    flying      94         94       50          50     66
11   Butterfree   bug    flying      45         90       50          80     70
414      Combee   bug    flying      30         30       42          42     70
213   Heracross   bug  fighting     185         40      115         105     75
211      Scizor   bug     steel     150         65      140         100     75
793    Buzzwole   bug  fighting     139         53      139          53     79
766      Wimpod   bug     water      35         20       40          30     80
283  Masquerain   bug    flying      60        100       62          82     80
741    Cutiefly   bug     fairy      45         55       40          40     84
312     Volbeat   bug       NaN      73         47       75          85     85
165      Ledian   bug    flying      35         55       50         110     85
313    Illumise   bug       NaN      47         73       75          85     85
665    Vivillon   bug    flying      52         90       50          50     89
48     Venomoth   bug    poison      65         90       60          75     90
541    Leavanny   bug     grass     103         70       80          80     92
468     Yanmega   bug    flying      76        116       86          56     95
192       Yanma   bug    flying      65         75       45          45     95
648    Genesect   bug     steel     120        120       95          95     99
636   Volcarona   bug      fire      60        135       65         105    100
126      Pinsir   bug       NaN     155         65      120          90    105
122     Scyther   bug    flying     110         55       80          80    105
595  Galvantula   bug  electric      77         97       60          60    108
631      Durant   bug     steel     109         48      112          48    109
544   Scolipede   bug    poison     100         55       89          69    112
742    Ribombee   bug     fairy      55         95       60          70    124
616    Accelgor   bug       NaN      70        100       40          60    145
14     Beedrill   bug    poison     150         15       40          80    145
794   Pheromosa   bug  fighting     137        137       37          37    151
290     Ninjask   bug    flying      90         50       45          50    160

[72 rows x 8 columns]

In [159]:
legendata = legendata[['pokedex_number','name','type1','type2','attack','defense','sp_attack','sp_defense','speed']]

In [160]:
legendata[legendata['type1']=='bug']

,pokedex_number,name,type1,type2,attack,defense,sp_attack,sp_defense,speed
648,649,Genesect,bug,steel,120,95,120,95,99
793,794,Buzzwole,bug,fighting,139,139,53,53,79
794,795,Pheromosa,bug,fighting,137,37,137,37,151